apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebusd
spec:
  selector:
    matchLabels:
      app: ebusd
      release: ebusd
  template:
    metadata:
      labels:
        app: ebusd
        release: ebusd
    spec:
      containers:
      - image: john30/ebusd:latest
        imagePullPolicy: Always
        name: ebusd
        ports:
        - containerPort: 8888
          name: http
          protocol: TCP
        env:
        - name: PUID
          value: "3000"
        - name: PGID
          value: "3000"
        - name: EBUSD_SCANCONFIG
          value: ''
        - name: EBUSD_DEVICE
          value: ens:172.21.4.2:9999
        - name: EBUSD_MQTTHOST
          value: '172.21.0.3'
        - name: EBUSD_MQTTPORT
          value: '1883'
        - name: EBUSD_MQTTINT
          value: '/etc/ebusd/mqtt-hassio.cfg'
        - name: EBUSD_MQTTJSON
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
