apiVersion: v1
kind: Service
metadata:
  name: ebusd-service    # < name of the service
  namespace: ebusd # < namespace where place the deployment and pods
spec:
  selector:
    app: ebusd # < reference to the deployment (connects with this deployment)
  type: LoadBalancer
  ports:
    - name: ebusd
      protocol: TCP
      port: 8888
  loadBalancerIP: 172.21.3.12