---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: code-ingress
  namespace: code
  annotations: 
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/websocket-timeout: "8h"
    traefik.ingress.kubernetes.io/client-body-timeout: "8h"
    traefik.ingress.kubernetes.io/client-header-timeout: "8h"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`code.olympus.mangelschots.org`)
      kind: Rule
      services:
        - name: code-service
          port: 8443
          scheme: http
          responseForwarding:
            flushInterval: 100ms
  tls:
    secretName: olympus-mangelschots-org-tls
