apiVersion: v1
kind: PersistentVolume
metadata:
  name: heimdall-pv-config   # < name of the persistent volume ("pv") in kubenetes
  namespace: heimdall     # < namespace where place the pv
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany       # < Multiple pods can write to storage 
  persistentVolumeReclaimPolicy: Retain   # < The persistent volume can reclaimed 
  path: /mnt/nfs/heimdall
