image:
  repository: tccr.io/truecharts/heimdall
  tag: v2.4.13@sha256:8138f65f84c423abd930250663a310788b4bb68ec0ba155376b4a972eeada14a
  pullPolicy: IfNotPresent

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10014
        targetPort: 80

probes:
  startup:
    enabled: true

persistence:
  config:
    enabled: true
    type: "emptydir"
    mountPath: "/config"

portal:
  enabled: false

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik-internal"
    hosts:
      host: "heimdall.olympus.mangelschots.org"
    tls:
      secretName: olympus-mangelschots-org-tls

