---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lidarr-kim-ingress
  namespace: lidarr-kim
  annotations: 
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`lidarr-kim.olympus.mangelschots.org`)
      kind: Rule
      services:
        - name: lidarr-kim-service
          port: 8686
  tls:
    secretName: olympus-mangelschots-org-tls
