apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual
spec:
  selector:
    matchLabels:
      app: actual
      release: actual
  template:
    metadata:
      labels:
        app: actual
        release: actual
    spec:
     volumes:
      - name: actual-data  # < linkname of the volume for the pvc
        hostPath:
          path: /mnt/k3s/actual-data # < pvc name we created in the previous yaml
      containers:
      - image: actualbudget/actual-server:latest
        imagePullPolicy: Always
        name: actual
        ports:
        - containerPort: 5006
          name: actual
          protocol: TCP
        env:
        - name: PUID
          value: "3000"
        - name: PGID
          value: "3000"
        volumeMounts:
          - mountPath: /data
            name: actual-data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
