apiVersion: apps/v1
kind: Deployment
metadata:
  name: modbusproxy
spec:
  selector:
    matchLabels:
      app: modbusproxy
      release: modbusproxy
  template:
    metadata:
      labels:
        app: modbusproxy
        release: modbusproxy
    spec:
      volumes:
      - name: modbusproxy-data  # < linkname of the volume for the pvc
        hostPath:
          path: /mnt/k3s/modbusproxy-data # < pvc name we created in the previous yaml
      containers:
      - image: tiagocoutinho/modbus-proxy:latest
        imagePullPolicy: Always
        name: modbusproxy
        ports:
        - containerPort: 1502
          name: modbusproxy1
          protocol: TCP
        env:
        volumeMounts:
          - mountPath: /config
            name: modbusproxy-data
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
