apiVersion: v1
kind: Service
metadata:
  name: grocy-service    # < name of the service
  namespace: grocy # < namespace where place the deployment and pods
spec:
  selector:
    app: grocy # < reference to the deployment (connects with this deployment)
  ports:
    - name: webinterface
      protocol: TCP
      port: 80
