---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: iscsi-pvc-paperless-data
    namespace: paperless-ngx
    labels:
      app: paperless-ngx
    annotations:
      volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
    storageClassName: freenas-nfs-csi
    accessModes:
     - ReadWriteOnce
    resources:
     requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: iscsi-pvc-paperless-media
    namespace: paperless-ngx
    labels:
      app: paperless-ngx
    annotations:
      volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
    storageClassName: freenas-nfs-csi
    accessModes:
     - ReadWriteOnce
    resources:
     requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: iscsi-pvc-paperless-consume
    namespace: paperless-ngx
    labels:
      app: paperless-ngx
    annotations:
      volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
    storageClassName: freenas-nfs-csi
    accessModes:
     - ReadWriteOnce
    resources:
     requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: iscsi-pvc-paperless-export
    namespace: paperless-ngx
    labels:
      app: paperless-ngx
    annotations:
      volume.beta.kubernetes.io/storage-class: "freenas-nfs-csi"
spec:
    storageClassName: freenas-nfs-csi
    accessModes:
     - ReadWriteOnce
    resources:
     requests:
      storage: 500Mi