apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr-dutch
spec:
  selector:
    matchLabels:
      app: radarr-dutch
      release: radarr-dutch
  template:
    metadata:
      labels:
        app: radarr-dutch
        release: radarr-dutch
    spec:
      volumes:
      - name: radarr-dutch-config  # < linkname of the volume for the pvc
        hostPath:
          path: /mnt/k3s/radarr-config # < pvc name we created in the previous yaml
      - name: radarr-dutch-movies
        hostPath:
          path: /mnt/nederlandse_films
      - name: radarr-dutch-downloads
        hostPath:
          path: /mnt/downloads
      containers:
      - image: linuxserver/radarr:latest
        imagePullPolicy: Always
        name: radarr-dutch
        ports:
        - containerPort: 7878
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: radarr-dutch-config
        - mountPath: /data/movies
          name: radarr-dutch-movies
        - mountPath: /data/downloads
          name: radarr-dutch-downloads 
        env:
        - name: PUID
          value: "3000"
        - name: PGID
          value: "3000"

