apiVersion: v1
kind: Service
metadata:
  name: radarr-dutch-service    # < name of the service
  namespace: radarr-dutch # < namespace where place the deployment and pods
spec:
  selector:
    app: radarr-dutch # < reference to the deployment (connects with this deployment)
  ports:
    - name: webinterface
      protocol: TCP
      port: 7878