apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-pvc        # < name of the persistent volume claim ("pvc'")
  namespace: heimdall       # < namespace where place the pvc

spec:
  storageClassName: "" 
  volumeName: heimdall-config-pv # < the pv it will "claim" to storage. Created in the previous yaml.
  accessModes:
    - ReadWriteMany         # < Multiple pods can write to storage. Same value as pv
  volumeMode: Filesystem
