---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ublparser-backend-ingress
  namespace: ublparser
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ublparser-backend.mangelschots.org`)
      kind: Rule
      services:
        - name: ublparser-backend-service
          port: 5000
  tls:
    secretName: mangelschots-org-tls

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ublparser-ingress
  namespace: ublparser
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ublparser.mangelschots.org`)
      kind: Rule
      services:
        - name: ublparser-service
          port: 5000
  tls:
    secretName: mangelschots-org-tls
