---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-mangelschots-org
  namespace: authelia 
spec:
  secretName: auth-mangelschots-org-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "auth.mangelschots.org"
  dnsNames:
  - "start.mangelschots.org"
