---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mangelschots-org
  namespace: traefik
spec:
  secretName: mangelschots-org-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.mangelschots.org"
  dnsNames:
  - "mangelschots.org"
  - "*.mangelschots.org"
