---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: requests-mangelschots-org
  namespace: heimdall-media 
spec:
  secretName: requests-mangelschots-org-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "requests.mangelschots.org"
  dnsNames:
  - "requests.mangelschots.org"
