---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin-ingress
  namespace: jellyfin
  annotations: 
    kubernetes.io/ingress.class: traefik-internal
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyfin.olympus.mangelschots.org`)
      kind: Rule
      services:
        - name: jellyfin-service
          port: 8096
  tls:
    secretName: olympus-mangelschots-org-tls
