apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft        # < name of the deployment
  namespace: minecraft   # < namespace where place the deployment and pods
  labels:
    app: minecraft       # < label for tagging and reference
spec:
  replicas: 1           # < number of pods to deploy
  selector:
    matchLabels:
      app: minecraft
  strategy:
    rollingUpdate:
      maxSurge: 0       # < The number of pods that can be created above the desired amount of pods during an update
      maxUnavailable: 1 # < The number of pods that can be unavailable during the update process
    type: RollingUpdate # < New pods are added gradually, and old pods are terminated gradually
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      volumes:
      - name: minecraft-data  # < linkname of the volume for the pvc
        hostPath:
          path: /mnt/k3s/minecraft-data # < pvc name we created in the previous yaml

      containers:
      - image: itzg/minecraft-server # < the name of the docker image we will use
        name: minecraft                      # < name of container
        imagePullPolicy: Always             # < always use the latest image when creating container/pod
        env:                                # < the environment variables required (see container documentation)
        - name: PGID
          value: "568" # < group "user"
        - name: PUID
          value: "568" # < user "docker"
        - name: TZ
          value: Europe/Brussels
        - name: EULA
          value: True
        ports:                              # < the ports required (see container documentation)
         - containerPort: 25565
           name: minecraft
           protocol: TCP
        volumeMounts:                       # < the volume mount in the container. Look at the relation volumelabel->pvc->pv
         - mountPath: /data               # < mount location in the container
           name: minecraft-data               # < volumelabel configured earlier in the yaml file              # < subfolder in the nfs share to be mounted
