---
- name: prep nodes
  hosts: all
  become: true

  vars:
    nfs_server: 172.21.0.4     # IP address of the NFS server

    nfs_shares:
      - { share: /mnt/large_pool/k3s, mount: /mnt/k3s }
      - { share: /mnt/large_pool/series, mount: /mnt/series }
      - { share: /mnt/large_pool/downloads, mount: /mnt/downloads }
      - { share: /mnt/large_pool/movies, mount: /mnt/movies}
      - { share: /mnt/large_pool/nederlandse_films, mount: /mnt/nederlandse_films}
      - { share: /mnt/large_pool/k3s_nomap, mount: /mnt/k3s_nomap }
      - { share: /mnt/large_pool/songs-kim, mount: /mnt/kim-songs}
      # Add more NFS shares here as needed
  tasks:
    - name: Install dependencies
      apt:
        pkg:
          - nfs-common
          - cifs-utils
          - open-iscsi
          - lsscsi
          - sg3-utils
          - multipath-tools
          - scsitools
        state: present

    - name: Create mount point directories
      file:
        path: "{{ item.mount }}"
        state: directory
      loop: "{{ nfs_shares }}"

    - name: Mount NFS shares
      mount:
        src: "{{ nfs_server }}:{{ item.share }}"
        path: "{{ item.mount }}"
        fstype: nfs
        opts: rw,noatime,nolock,hard,intr
        state: mounted
      loop: "{{ nfs_shares }}"

    - name: Add entries to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "{{ nfs_server }}:{{ item.share }} {{ item.mount }} nfs rw,noatime,nolock,hard,intr 0 0"
        state: present
      loop: "{{ nfs_shares }}"
