---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zigbee2mqtt-mangelschots-org
  namespace: zigbee2mqtt 
spec:
  secretName: zigbee2mqtt-mangelschots-org-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "zigbee2mqtt.mangelschots.org"
  dnsNames:
  - "zigbee2mqtt.mangelschots.org"
