apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
      release: influxdb
  template:
    metadata:
      labels:
        app: influxdb
        release: influxdb
    spec:
      volumes:
      - name: influxdb-volume
        persistentVolumeClaim:
          claimName: iscsi-pvc-influxdb
      containers:
      - image: influxdb
        imagePullPolicy: Always
        name: influxdb
        ports:
        - containerPort: 8086
          name: http
          protocol: TCP
        volumeMounts:
          - name: influxdb-volume
            mountPath: /var/lib/influxdb2
        env:
        - name: PUID
          value: "568"
        - name: PGID
          value: "568"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
