---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: iscsi-pvc-influxdb
    namespace: influxdb
    labels:
      app: influxdb
    annotations:
      volume.beta.kubernetes.io/storage-class: "freenas-iscsi-csi"
spec:
    storageClassName: freenas-iscsi-csi
    accessModes:
     - ReadWriteOnce
    resources:
     requests:
      storage: 500Mi